// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


// `include "common_cells/assertions.svh"

module custom_axi_ip_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 4
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output custom_axi_ip_reg_pkg::custom_axi_ip_reg2hw_t reg2hw,  // Write
    input custom_axi_ip_reg_pkg::custom_axi_ip_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import custom_axi_ip_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;

  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] din_wd;
  logic din_we;
  logic [31:0] dout_qs;
  logic dout_re;
  logic enable_wd;
  logic enable_we;
  logic [1:0] status_qs;
  logic status_re;

  // Register instances
  // R[din]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("WO"),
      .RESVAL  (32'h0)
  ) u_din (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(din_we),
      .wd(din_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.din.q),

      .qs()
  );


  // R[dout]: V(True)

  prim_subreg_ext #(
      .DW(32)
  ) u_dout (
      .re (dout_re),
      .we (1'b0),
      .wd ('0),
      .d  (hw2reg.dout.d),
      .qre(),
      .qe (),
      .q  (),
      .qs (dout_qs)
  );

  // R[enable]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("WO"),
      .RESVAL  (1'h0)
  ) u_enable (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(enable_we),
      .wd(enable_wd),

      // from internal hardware
      .de(hw2reg.enable.de),
      .d (hw2reg.enable.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.enable.q),

      .qs()
  );


  // R[status]: V(True)

  prim_subreg_ext #(
      .DW(2)
  ) u_status (
      .re (status_re),
      .we (1'b0),
      .wd ('0),
      .d  (hw2reg.status.d),
      .qre(),
      .qe (),
      .q  (),
      .qs (status_qs)
  );


  logic [3:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == CUSTOM_AXI_IP_DIN_OFFSET);
    addr_hit[1] = (reg_addr == CUSTOM_AXI_IP_DOUT_OFFSET);
    addr_hit[2] = (reg_addr == CUSTOM_AXI_IP_ENABLE_OFFSET);
    addr_hit[3] = (reg_addr == CUSTOM_AXI_IP_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(CUSTOM_AXI_IP_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(CUSTOM_AXI_IP_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(CUSTOM_AXI_IP_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(CUSTOM_AXI_IP_PERMIT[3] & ~reg_be)))));
  end

  assign din_we = addr_hit[0] & reg_we & !reg_error;
  assign din_wd = reg_wdata[31:0];

  assign dout_re = addr_hit[1] & reg_re & !reg_error;

  assign enable_we = addr_hit[2] & reg_we & !reg_error;
  assign enable_wd = reg_wdata[0];

  assign status_re = addr_hit[3] & reg_re & !reg_error;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = dout_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[1:0] = status_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  // `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module custom_axi_ip_reg_top_intf #(
    parameter  int AW = 4,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output custom_axi_ip_reg_pkg::custom_axi_ip_reg2hw_t reg2hw,  // Write
    input custom_axi_ip_reg_pkg::custom_axi_ip_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  custom_axi_ip_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule